//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.13 at 12:04:13 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://by.it.sendetskaya.jd02_09", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.sendetskaya.jd02_09;
