//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.15 at 12:43:52 AM MSK 
//


package by.it.vshelukhin.jd02_09.TaskB_C;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Student complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Student"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Univer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Kurs" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="Facultet" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Goods" type="{myspace}Goods"/&gt;
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Student", propOrder = {
    "univer",
    "kurs",
    "facultet",
    "goods",
    "price"
})
public class Student {

    @XmlElement(name = "Univer", required = true)
    protected String univer;
    @XmlElement(name = "Kurs", required = true)
    protected BigInteger kurs;
    @XmlElement(name = "Facultet", required = true)
    protected String facultet;
    @XmlElement(name = "Goods", required = true)
    protected Goods goods;
    @XmlElement(name = "Price", required = true)
    protected String price;

    /**
     * Gets the value of the univer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniver() {
        return univer;
    }

    /**
     * Sets the value of the univer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniver(String value) {
        this.univer = value;
    }

    /**
     * Gets the value of the kurs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKurs() {
        return kurs;
    }

    /**
     * Sets the value of the kurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKurs(BigInteger value) {
        this.kurs = value;
    }

    /**
     * Gets the value of the facultet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultet() {
        return facultet;
    }

    /**
     * Sets the value of the facultet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultet(String value) {
        this.facultet = value;
    }

    /**
     * Gets the value of the goods property.
     * 
     * @return
     *     possible object is
     *     {@link Goods }
     *     
     */
    public Goods getGoods() {
        return goods;
    }

    /**
     * Sets the value of the goods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Goods }
     *     
     */
    public void setGoods(Goods value) {
        this.goods = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    @Override
    public String toString() {
        return "Student{" +
                "univer='" + univer + '\'' +
                ", kurs=" + kurs +
                ", facultet='" + facultet + '\'' +
                ", goods=" + goods +
                ", price='" + price + '\'' +
                '}';
    }
}
