//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.14 at 10:47:29 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jd02_09.patsko.it.by/",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.patsko.jd02_09;
