//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.23 at 05:09:51 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.it.by/sevashko/jd02_10/taskB", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.sevashko.jd02_10.taskB;
